# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1e515df2493e0b34e519ca28e2c6dc8d5bffe879601b6321dd372e74ed3a1ce0cff76e56d8b05a6e5bc7317b37b63490640cdfd5702c783e09fa9245459629b

test:
  secret_key_base: f917d82b68ff92d5926f70c193620e6bd4e6b3c5b5c18871e06df054cceb687d77e162ff8ccae6656ece3f3e5b82587124238d56dc13f2ee6ccf5d2823f2e084

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
